version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: scrumplanner
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
