name: Build & Dockerize Backend

on:
  repository_dispatch:
    types: [frontend-build-released]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download frontend release asset
        run: |
          mkdir -p src/main/resources/static
          gh release download --repo nallayasami/scrum-planner-angular-fe --pattern "*" -D src/main/resources/static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: mvn clean package -DskipTests
      - run: docker build -t scrum-planner:latest .
